@startuml
'!include ../EIP_Elements.puml
!include ../dist/EIP-PlantUML.puml
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4.puml

LAYOUT_LEFT_RIGHT
Message(alias1)
Message(alias2, "label")
CommandMessage(alias3)
CommandMessage(alias4, "label")
DocumentMessage(alias5)
DocumentMessage(alias6, "label")
EventMessage(alias7)
EventMessage(alias8, "label")
RequestReply(alias9)
RequestReply(alias10, "label")
ReturnAddress(alias11)
ReturnAddress(alias12, "label")
CorrelationIdentifier(alias13)
CorrelationIdentifier(alias14, "label")
MessageSequence(alias15)
MessageSequence(alias16, "label")
MessageExpiration(alias17)
MessageExpiration(alias18, "label")

Filter(alias18a)
Filter(alias18b, "label")
ContentFilter(alias19)
ContentFilter(alias20, "label")
MessageRouter(alias21)
MessageRouter(alias22, "label")
ContentBasedRouter(alias23)
ContentBasedRouter(alias24, "label")
MessageFilter(alias25)
MessageFilter(alias26, "label")
DynamicRouter(alias27, rulebase1)
DynamicRouter(alias28, "label", rulebase2)
RecipientList(alias29)
RecipientList(alias30, "label")
Splitter(alias31)
Splitter(alias32, "label")
Aggregator(alias33)
Aggregator(alias34, "label")
Resequencer(alias35)
Resequencer(alias36, "label")
ScatterGather(alias36a)
ScatterGather(alias36b, "label")
ComposedMessageProcessor(alias37)
ComposedMessageProcessor(alias38, "label")
RoutingSlip(alias39)
RoutingSlip(alias40, "label")
ProcessManager(alias41)
ProcessManager(alias42, "label")
MessageBroker(alias43)
MessageBroker(alias44, "label")

MessageTranslator(alias45)
MessageTranslator(alias46, "label")
Wrapper(alias47)
Wrapper(alias48, "label")
Unwrapper(alias49)
Unwrapper(alias50, "label")
DataEnricher(alias51, datasource1)
DataEnricher(alias52, "label", datasource2)
ContentFilter(alias53)
ContentFilter(alias54, "label")
Normalizer(alias55)
Normalizer(alias56, "label")

MessageEndpoint(alias57)
MessageEndpoint(alias58, "label")
MessagingGateway(alias59)
MessagingGateway(alias60, "label")
MessagingMapper(alias61)
MessagingMapper(alias62, "label")
TransactionalProducer(alias63)
TransactionalProducer(alias64, "label")
TransactionalConsumer(alias65)
TransactionalConsumer(alias66, "label")
PollingConsumer(alias67)
PollingConsumer(alias68, "label")
EventDrivenConsumer(alias69)
EventDrivenConsumer(alias70, "label")
MessageDispatcher(alias71)
MessageDispatcher(alias72, "label")
SelectiveConsumer(alias73)
SelectiveConsumer(alias74, "label")
DurableSubscriber(alias75)
DurableSubscriber(alias76, "label")
NonDurableSubscriber(alias77)
NonDurableSubscriber(alias78, "label")
ServiceActivator(alias79)
ServiceActivator(alias80, "label")

MsgChannel(alias81)
MsgChannel(alias82, "label")
P2PChannel(alias83)
P2PChannel(alias84, "label")
PubSubChannel(alias85)
PubSubChannel(alias86, "label")
DatatypeChannel(alias87)
DatatypeChannel(alias88, "label")
InvalidMsgChannel(alias89)
InvalidMsgChannel(alias90, "label")
DeadLetterChannel(alias91)
DeadLetterChannel(alias92, "label")
ChannelAdapterLeft(alias93)
ChannelAdapterLeft(alias94, "label")
ChannelAdapterRight(alias95)
ChannelAdapterRight(alias96, "label")
MsgBridge(alias97)
MsgBridge(alias98, "label")
MsgBus(alias99)
MsgBus(alias100, "label")

ControlBus(alias101)

Detour(alias102)
Detour(alias103, "label")

WireTap(alias104)
WireTap(alias105, "label")
MessageStore(alias106)
MessageStore(alias107, "label")
SmartProxy(alias108)
SmartProxy(alias109, "label")
TestMessage(alias110)
TestMessage(alias111, "label")
ChannelPurger(alias112)
ChannelPurger(alias113, "label")

Send(alias81,alias95)
Filter(f1)
Filter(f2)
Pipe(f1,f2)


@enduml
