sprite $scatter_gather [156x49/16z] {
pPc7TYiX34GbiRtT___QLzn8JxIHWNkAkws31kqCbZ1iNfAqIGTWqYBAXRxTqa1QO-B1DcfZGXiVFUtRQQm2N5Qg1zX4H1TOJMeplboajD6zN4gLUYHWaK_G
2UYa3YkGlgvzWzcaD3qmolSCm511_Zz3PzYJbC6lemwOj8ZyPt6ZuzE7tWwOdCFMeA4NB-kyWS8nO9DVenEG998vy1lJ3hC6NicdS7NqXKQP7vjFRGpJV7zm
ZZ8rfx5Ih-R9TsVn0E3ixT5bIUy_CjOYClb76HVKszj9hwLzL9pUC5Fbod96h2DNpcoC3lXe-17CGHol1zc5r0FTcNZg7pSw00jNBAFobbpkuXuUPrfgoxMJ
mFS29qioULS1mEjErfG_cznUBJqnEGudPcD6WLqb6bjWiPXiC4WWEW9TPAQoIE-W1R9efcwo6O4-r3gN3t_-95tUQPO_WSWEFTohbKysLk34oo_hd0rAezyd
wNJ0hFKEK-U0B5hWv6Q7xTM5JgKo2Xpwoh_P2ej9RV8Y9IwCEJcsmapE2wEs-lU7IeFaqXe4mAHHr2IMlm
}

